version: '1'
services:
    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16
        restart: always

    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017 --oplogSize 16
        links:
            - mongo-cnf-2:mongo-cnf-2
        restart: always

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]
